#!/usr/bin/env python3
"""Shared rendering helpers for the per-session report and the dashboard.

Design decision worth keeping: the *numbers* are computed here and the *words*
come from a narrative file the reviewer authors. Nothing in a report is prose
generated by a script, and no tally in a report is a number typed by hand.
"""

import html
import re
from pathlib import Path

ASSETS = Path(__file__).resolve().parent.parent / "assets"

GRADE_CLASS = {
    "wrong_high": "crit",
    "wrong_contained": "warn",
    "incomplete": "info",
    "correct": "good",
    "unverifiable": "",
}
GRADE_LABEL = {
    "wrong_high": "Wrong — high impact",
    "wrong_contained": "Wrong — contained",
    "incomplete": "Incomplete or imprecise",
    "correct": "Verified correct",
    "unverifiable": "Not settled from source",
}
GRADE_ORDER = ["wrong_high", "wrong_contained", "incomplete", "correct", "unverifiable"]

FONTS = (
    '<link rel="preconnect" href="https://fonts.googleapis.com">'
    '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>'
    '<link rel="stylesheet" href="https://fonts.googleapis.com/css2?'
    "family=Zilla+Slab:wght@500;600;700&"
    "family=Source+Sans+3:ital,wght@0,400;0,600;0,700;1,400&"
    'family=IBM+Plex+Mono:wght@400;500&display=swap">'
)


def e(s) -> str:
    return html.escape(str(s if s is not None else ""))


def rich(s) -> str:
    """Escape, then re-allow the small inline vocabulary a reviewer writes:
    `code`, **bold**, *italic*. Keeps authored prose readable without letting
    arbitrary HTML through from a transcript quote."""
    out = e(s)
    out = re.sub(r"`([^`]+)`", r"<code>\1</code>", out)
    out = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", out)
    out = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"<em>\1</em>", out)
    return out


def head(title: str, standalone: bool) -> str:
    """`standalone` embeds the CSS (for local files and PDF export); the artifact
    build links nothing external beyond fonts, so it embeds too."""
    css = (ASSETS / "report.css").read_text(encoding="utf-8")
    pcss = (ASSETS / "print.css").read_text(encoding="utf-8")
    doc = f"<title>{e(title)}</title>\n{FONTS}\n<style>\n{css}\n{pcss}\n</style>\n"
    if standalone:
        return (
            "<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n"
            '<meta name="viewport" content="width=device-width,initial-scale=1">\n'
            "<style>html{color-scheme:light}body{margin:0}</style>\n" + doc + "</head>\n<body>\n"
        )
    return doc


def tail(standalone: bool) -> str:
    return "</body>\n</html>\n" if standalone else ""


def tally(pairs) -> str:
    cells = "".join(
        f'<div><span class="n {cls}">{n}</span><span class="k">{e(label)}</span></div>'
        for n, label, cls in pairs
    )
    return f'<div class="tally">{cells}</div>'


def meta(pairs) -> str:
    cells = "".join(f"<div><dt>{e(k)}</dt><dd>{rich(v)}</dd></div>" for k, v in pairs)
    return f'<dl class="meta">{cells}</dl>'


def finding(f: dict, num: str) -> str:
    cls = GRADE_CLASS.get(f.get("grade", ""), "")
    parts = [f'<div class="finding {cls}">', '<div class="f-head">']
    parts.append(f'<span class="f-num">{e(num)}</span>')
    parts.append(f'<h3 class="f-title">{rich(f.get("title") or f.get("claim_id",""))}</h3>')
    if f.get("stamp"):
        parts.append(f'<span class="stamp">{e(f["stamp"])}</span>')
    parts.append("</div>")

    if f.get("quote"):
        parts.append(f'<p class="said">{rich(f["quote"])}</p>')
    for para in (f.get("body") or ([f["reality"]] if f.get("reality") else [])):
        parts.append(f"<p>{rich(para)}</p>")
    if f.get("product_bug"):
        parts.append('<p><span class="flag">Product bug</span></p>')
    if f.get("say_instead"):
        parts.append(f'<div class="fix"><b>Say instead</b>{rich(f["say_instead"])}</div>')
    if f.get("evidence"):
        parts.append(
            '<div class="evidence"><b>Evidence</b>' + e(" · ".join(f["evidence"])) + "</div>"
        )
    elif f.get("grade") == "unverifiable":
        parts.append('<div class="evidence"><b>Evidence</b>not settled from source</div>')
    parts.append("</div>")
    return "\n".join(parts)


def table(headers, rows) -> str:
    th = "".join(f"<th>{e(h)}</th>" for h in headers)
    body = "".join(
        "<tr>" + "".join(f"<td>{rich(c)}</td>" for c in r) + "</tr>" for r in rows
    )
    return f'<div class="tw"><table><thead><tr>{th}</tr></thead><tbody>{body}</tbody></table></div>'
